package com.Wsdl2Code.WebServices.WSAmandaService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 1/24/2016 9:16:23 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import com.Wsdl2Code.WebServices.WSAmandaService.wsPeopleGroupRequest;
import com.Wsdl2Code.WebServices.WSAmandaService.KvmSerializable_ws;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class getPeopleGroup implements KvmSerializable_ws {
    
    public wsPeopleGroupRequest wsPeopleGroupRequest;
    
    public getPeopleGroup(){}
    
    public getPeopleGroup(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("wsPeopleGroupRequest"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("wsPeopleGroupRequest");
            wsPeopleGroupRequest =  new wsPeopleGroupRequest (j);
            
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return wsPeopleGroupRequest;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 1;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = wsPeopleGroupRequest.class;
                info.name = "wsPeopleGroupRequest";
                break;
        }
    }
    
    @Override
    public String getInnerText() {
        return null;
    }
    
    
    @Override
    public void setInnerText(String s) {
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
