package com.Wsdl2Code.WebServices.WSAmandaService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 1/24/2016 9:16:23 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import com.Wsdl2Code.WebServices.WSAmandaService.KvmSerializable_ws;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class wsPaymentDetailsRequest implements KvmSerializable_ws {
    
    public int feeRSN;
    public boolean feeRSNSpecified;
    public double paymentAmount;
    public boolean paymentAmountSpecified;
    
    public wsPaymentDetailsRequest(){}
    
    public wsPaymentDetailsRequest(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("feeRSN"))
        {
            Object obj = soapObject.getProperty("feeRSN");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                feeRSN = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                feeRSN = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("feeRSNSpecified"))
        {
            Object obj = soapObject.getProperty("feeRSNSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                feeRSNSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                feeRSNSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("paymentAmount"))
        {
            Object obj = soapObject.getProperty("paymentAmount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                paymentAmount = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                paymentAmount = (Double) obj;
            }
        }
        if (soapObject.hasProperty("paymentAmountSpecified"))
        {
            Object obj = soapObject.getProperty("paymentAmountSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                paymentAmountSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                paymentAmountSpecified = (Boolean) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return feeRSN;
            case 1:
                return feeRSNSpecified;
            case 2:
                return paymentAmount;
            case 3:
                return paymentAmountSpecified;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 4;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "feeRSN";
                break;
            case 1:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "feeRSNSpecified";
                break;
            case 2:
                info.type = Double.class;
                info.name = "paymentAmount";
                break;
            case 3:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "paymentAmountSpecified";
                break;
        }
    }
    
    @Override
    public String getInnerText() {
        return null;
    }
    
    
    @Override
    public void setInnerText(String s) {
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
