package com.Wsdl2Code.WebServices.WSAmandaService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 1/24/2016 9:16:23 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import com.Wsdl2Code.WebServices.WSAmandaService.VectorwsValidInfoValue;
import com.Wsdl2Code.WebServices.WSAmandaService.KvmSerializable_ws;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class wsPropertyValidInfo implements KvmSerializable_ws {
    
    public String comments;
    public String displayFormat;
    public int displayOrder;
    public boolean displayOrderSpecified;
    public String infoGroup;
    public int pickSelectCode;
    public boolean pickSelectCodeSpecified;
    public int propertyInfoCode;
    public boolean propertyInfoCodeSpecified;
    public String propertyInfoDesc;
    public String propertyinfoType;
    public VectorwsValidInfoValue validInfoValues;
    
    public wsPropertyValidInfo(){}
    
    public wsPropertyValidInfo(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("comments"))
        {
            Object obj = soapObject.getProperty("comments");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                comments = j.toString();
            }else if (obj!= null && obj instanceof String){
                comments = (String) obj;
            }
        }
        if (soapObject.hasProperty("displayFormat"))
        {
            Object obj = soapObject.getProperty("displayFormat");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                displayFormat = j.toString();
            }else if (obj!= null && obj instanceof String){
                displayFormat = (String) obj;
            }
        }
        if (soapObject.hasProperty("displayOrder"))
        {
            Object obj = soapObject.getProperty("displayOrder");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                displayOrder = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                displayOrder = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("displayOrderSpecified"))
        {
            Object obj = soapObject.getProperty("displayOrderSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                displayOrderSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                displayOrderSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("infoGroup"))
        {
            Object obj = soapObject.getProperty("infoGroup");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                infoGroup = j.toString();
            }else if (obj!= null && obj instanceof String){
                infoGroup = (String) obj;
            }
        }
        if (soapObject.hasProperty("pickSelectCode"))
        {
            Object obj = soapObject.getProperty("pickSelectCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                pickSelectCode = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                pickSelectCode = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("pickSelectCodeSpecified"))
        {
            Object obj = soapObject.getProperty("pickSelectCodeSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                pickSelectCodeSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                pickSelectCodeSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("propertyInfoCode"))
        {
            Object obj = soapObject.getProperty("propertyInfoCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                propertyInfoCode = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                propertyInfoCode = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("propertyInfoCodeSpecified"))
        {
            Object obj = soapObject.getProperty("propertyInfoCodeSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                propertyInfoCodeSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                propertyInfoCodeSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("propertyInfoDesc"))
        {
            Object obj = soapObject.getProperty("propertyInfoDesc");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                propertyInfoDesc = j.toString();
            }else if (obj!= null && obj instanceof String){
                propertyInfoDesc = (String) obj;
            }
        }
        if (soapObject.hasProperty("propertyinfoType"))
        {
            Object obj = soapObject.getProperty("propertyinfoType");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                propertyinfoType = j.toString();
            }else if (obj!= null && obj instanceof String){
                propertyinfoType = (String) obj;
            }
        }
        if (soapObject.hasProperty("validInfoValues"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("validInfoValues");
            validInfoValues = new VectorwsValidInfoValue(j);
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return comments;
            case 1:
                return displayFormat;
            case 2:
                return displayOrder;
            case 3:
                return displayOrderSpecified;
            case 4:
                return infoGroup;
            case 5:
                return pickSelectCode;
            case 6:
                return pickSelectCodeSpecified;
            case 7:
                return propertyInfoCode;
            case 8:
                return propertyInfoCodeSpecified;
            case 9:
                return propertyInfoDesc;
            case 10:
                return propertyinfoType;
            case 11:
                return validInfoValues;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 12;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "comments";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "displayFormat";
                break;
            case 2:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "displayOrder";
                break;
            case 3:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "displayOrderSpecified";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "infoGroup";
                break;
            case 5:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "pickSelectCode";
                break;
            case 6:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "pickSelectCodeSpecified";
                break;
            case 7:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "propertyInfoCode";
                break;
            case 8:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "propertyInfoCodeSpecified";
                break;
            case 9:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "propertyInfoDesc";
                break;
            case 10:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "propertyinfoType";
                break;
            case 11:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "validInfoValues";
                break;
        }
    }
    
    @Override
    public String getInnerText() {
        return null;
    }
    
    
    @Override
    public void setInnerText(String s) {
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
