package com.Wsdl2Code.WebServices.WSAmandaService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 1/24/2016 9:16:23 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import com.Wsdl2Code.WebServices.WSAmandaService.KvmSerializable_ws;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class wsValidChecklist implements KvmSerializable_ws {
    
    public int accessCode;
    public boolean accessCodeSpecified;
    public int checklistCode;
    public boolean checklistCodeSpecified;
    public String checklistDesc;
    public String checklistDetail;
    public int checklistGroupCode;
    public boolean checklistGroupCodeSpecified;
    public String comments;
    
    public wsValidChecklist(){}
    
    public wsValidChecklist(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("accessCode"))
        {
            Object obj = soapObject.getProperty("accessCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                accessCode = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                accessCode = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("accessCodeSpecified"))
        {
            Object obj = soapObject.getProperty("accessCodeSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                accessCodeSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                accessCodeSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("checklistCode"))
        {
            Object obj = soapObject.getProperty("checklistCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                checklistCode = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                checklistCode = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("checklistCodeSpecified"))
        {
            Object obj = soapObject.getProperty("checklistCodeSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                checklistCodeSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                checklistCodeSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("checklistDesc"))
        {
            Object obj = soapObject.getProperty("checklistDesc");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                checklistDesc = j.toString();
            }else if (obj!= null && obj instanceof String){
                checklistDesc = (String) obj;
            }
        }
        if (soapObject.hasProperty("checklistDetail"))
        {
            Object obj = soapObject.getProperty("checklistDetail");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                checklistDetail = j.toString();
            }else if (obj!= null && obj instanceof String){
                checklistDetail = (String) obj;
            }
        }
        if (soapObject.hasProperty("checklistGroupCode"))
        {
            Object obj = soapObject.getProperty("checklistGroupCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                checklistGroupCode = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                checklistGroupCode = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("checklistGroupCodeSpecified"))
        {
            Object obj = soapObject.getProperty("checklistGroupCodeSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                checklistGroupCodeSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                checklistGroupCodeSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("comments"))
        {
            Object obj = soapObject.getProperty("comments");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                comments = j.toString();
            }else if (obj!= null && obj instanceof String){
                comments = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return accessCode;
            case 1:
                return accessCodeSpecified;
            case 2:
                return checklistCode;
            case 3:
                return checklistCodeSpecified;
            case 4:
                return checklistDesc;
            case 5:
                return checklistDetail;
            case 6:
                return checklistGroupCode;
            case 7:
                return checklistGroupCodeSpecified;
            case 8:
                return comments;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 9;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "accessCode";
                break;
            case 1:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "accessCodeSpecified";
                break;
            case 2:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "checklistCode";
                break;
            case 3:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "checklistCodeSpecified";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "checklistDesc";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "checklistDetail";
                break;
            case 6:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "checklistGroupCode";
                break;
            case 7:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "checklistGroupCodeSpecified";
                break;
            case 8:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "comments";
                break;
        }
    }
    
    @Override
    public String getInnerText() {
        return null;
    }
    
    
    @Override
    public void setInnerText(String s) {
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
