package com.Wsdl2Code.WebServices.WSAmandaService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 1/24/2016 9:16:23 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import com.Wsdl2Code.WebServices.WSAmandaService.KvmSerializable_ws;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class wsValidLookup implements KvmSerializable_ws {
    
    public String comments;
    public String lookDate10;
    public boolean lookDate10Specified;
    public String lookDate6;
    public boolean lookDate6Specified;
    public String lookDate7;
    public boolean lookDate7Specified;
    public String lookDate8;
    public boolean lookDate8Specified;
    public String lookDate9;
    public boolean lookDate9Specified;
    public double lookUp1;
    public boolean lookUp1Specified;
    public double lookUp2;
    public boolean lookUp2Specified;
    public double lookUp3;
    public boolean lookUp3Specified;
    public double lookUp4;
    public boolean lookUp4Specified;
    public double lookUp5;
    public boolean lookUp5Specified;
    public double lookUp6;
    public boolean lookUp6Specified;
    public double lookUp7;
    public boolean lookUp7Specified;
    public double lookUp8;
    public boolean lookUp8Specified;
    public double lookUp9;
    public boolean lookUp9Specified;
    public int lookUpCode;
    public boolean lookUpCodeSpecified;
    public String lookUpDate;
    public boolean lookUpDateSpecified;
    public String lookUpDate2;
    public boolean lookUpDate2Specified;
    public String lookUpDate3;
    public boolean lookUpDate3Specified;
    public String lookUpDate4;
    public boolean lookUpDate4Specified;
    public String lookUpDate5;
    public boolean lookUpDate5Specified;
    public double lookUpFee;
    public boolean lookUpFeeSpecified;
    public String lookUpString;
    public String lookUpString2;
    public String lookUpString3;
    public String lookUpString4;
    public String lookUpString5;
    public String lookUpString6;
    public String lookUpString7;
    public String lookUpString8;
    public String lookUpString9;
    public String lookUpstring10;
    
    public wsValidLookup(){}
    
    public wsValidLookup(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("comments"))
        {
            Object obj = soapObject.getProperty("comments");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                comments = j.toString();
            }else if (obj!= null && obj instanceof String){
                comments = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookDate10"))
        {
            Object obj = soapObject.getProperty("lookDate10");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookDate10 = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookDate10 = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookDate10Specified"))
        {
            Object obj = soapObject.getProperty("lookDate10Specified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookDate10Specified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookDate10Specified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookDate6"))
        {
            Object obj = soapObject.getProperty("lookDate6");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookDate6 = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookDate6 = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookDate6Specified"))
        {
            Object obj = soapObject.getProperty("lookDate6Specified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookDate6Specified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookDate6Specified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookDate7"))
        {
            Object obj = soapObject.getProperty("lookDate7");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookDate7 = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookDate7 = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookDate7Specified"))
        {
            Object obj = soapObject.getProperty("lookDate7Specified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookDate7Specified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookDate7Specified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookDate8"))
        {
            Object obj = soapObject.getProperty("lookDate8");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookDate8 = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookDate8 = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookDate8Specified"))
        {
            Object obj = soapObject.getProperty("lookDate8Specified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookDate8Specified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookDate8Specified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookDate9"))
        {
            Object obj = soapObject.getProperty("lookDate9");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookDate9 = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookDate9 = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookDate9Specified"))
        {
            Object obj = soapObject.getProperty("lookDate9Specified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookDate9Specified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookDate9Specified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookUp1"))
        {
            Object obj = soapObject.getProperty("lookUp1");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUp1 = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                lookUp1 = (Double) obj;
            }
        }
        if (soapObject.hasProperty("lookUp1Specified"))
        {
            Object obj = soapObject.getProperty("lookUp1Specified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUp1Specified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookUp1Specified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookUp2"))
        {
            Object obj = soapObject.getProperty("lookUp2");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUp2 = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                lookUp2 = (Double) obj;
            }
        }
        if (soapObject.hasProperty("lookUp2Specified"))
        {
            Object obj = soapObject.getProperty("lookUp2Specified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUp2Specified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookUp2Specified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookUp3"))
        {
            Object obj = soapObject.getProperty("lookUp3");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUp3 = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                lookUp3 = (Double) obj;
            }
        }
        if (soapObject.hasProperty("lookUp3Specified"))
        {
            Object obj = soapObject.getProperty("lookUp3Specified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUp3Specified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookUp3Specified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookUp4"))
        {
            Object obj = soapObject.getProperty("lookUp4");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUp4 = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                lookUp4 = (Double) obj;
            }
        }
        if (soapObject.hasProperty("lookUp4Specified"))
        {
            Object obj = soapObject.getProperty("lookUp4Specified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUp4Specified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookUp4Specified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookUp5"))
        {
            Object obj = soapObject.getProperty("lookUp5");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUp5 = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                lookUp5 = (Double) obj;
            }
        }
        if (soapObject.hasProperty("lookUp5Specified"))
        {
            Object obj = soapObject.getProperty("lookUp5Specified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUp5Specified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookUp5Specified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookUp6"))
        {
            Object obj = soapObject.getProperty("lookUp6");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUp6 = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                lookUp6 = (Double) obj;
            }
        }
        if (soapObject.hasProperty("lookUp6Specified"))
        {
            Object obj = soapObject.getProperty("lookUp6Specified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUp6Specified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookUp6Specified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookUp7"))
        {
            Object obj = soapObject.getProperty("lookUp7");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUp7 = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                lookUp7 = (Double) obj;
            }
        }
        if (soapObject.hasProperty("lookUp7Specified"))
        {
            Object obj = soapObject.getProperty("lookUp7Specified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUp7Specified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookUp7Specified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookUp8"))
        {
            Object obj = soapObject.getProperty("lookUp8");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUp8 = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                lookUp8 = (Double) obj;
            }
        }
        if (soapObject.hasProperty("lookUp8Specified"))
        {
            Object obj = soapObject.getProperty("lookUp8Specified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUp8Specified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookUp8Specified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookUp9"))
        {
            Object obj = soapObject.getProperty("lookUp9");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUp9 = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                lookUp9 = (Double) obj;
            }
        }
        if (soapObject.hasProperty("lookUp9Specified"))
        {
            Object obj = soapObject.getProperty("lookUp9Specified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUp9Specified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookUp9Specified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookUpCode"))
        {
            Object obj = soapObject.getProperty("lookUpCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpCode = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                lookUpCode = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("lookUpCodeSpecified"))
        {
            Object obj = soapObject.getProperty("lookUpCodeSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpCodeSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookUpCodeSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookUpDate"))
        {
            Object obj = soapObject.getProperty("lookUpDate");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpDate = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookUpDate = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookUpDateSpecified"))
        {
            Object obj = soapObject.getProperty("lookUpDateSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpDateSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookUpDateSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookUpDate2"))
        {
            Object obj = soapObject.getProperty("lookUpDate2");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpDate2 = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookUpDate2 = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookUpDate2Specified"))
        {
            Object obj = soapObject.getProperty("lookUpDate2Specified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpDate2Specified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookUpDate2Specified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookUpDate3"))
        {
            Object obj = soapObject.getProperty("lookUpDate3");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpDate3 = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookUpDate3 = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookUpDate3Specified"))
        {
            Object obj = soapObject.getProperty("lookUpDate3Specified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpDate3Specified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookUpDate3Specified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookUpDate4"))
        {
            Object obj = soapObject.getProperty("lookUpDate4");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpDate4 = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookUpDate4 = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookUpDate4Specified"))
        {
            Object obj = soapObject.getProperty("lookUpDate4Specified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpDate4Specified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookUpDate4Specified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookUpDate5"))
        {
            Object obj = soapObject.getProperty("lookUpDate5");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpDate5 = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookUpDate5 = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookUpDate5Specified"))
        {
            Object obj = soapObject.getProperty("lookUpDate5Specified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpDate5Specified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookUpDate5Specified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookUpFee"))
        {
            Object obj = soapObject.getProperty("lookUpFee");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpFee = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                lookUpFee = (Double) obj;
            }
        }
        if (soapObject.hasProperty("lookUpFeeSpecified"))
        {
            Object obj = soapObject.getProperty("lookUpFeeSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpFeeSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                lookUpFeeSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lookUpString"))
        {
            Object obj = soapObject.getProperty("lookUpString");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpString = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookUpString = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookUpString2"))
        {
            Object obj = soapObject.getProperty("lookUpString2");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpString2 = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookUpString2 = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookUpString3"))
        {
            Object obj = soapObject.getProperty("lookUpString3");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpString3 = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookUpString3 = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookUpString4"))
        {
            Object obj = soapObject.getProperty("lookUpString4");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpString4 = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookUpString4 = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookUpString5"))
        {
            Object obj = soapObject.getProperty("lookUpString5");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpString5 = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookUpString5 = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookUpString6"))
        {
            Object obj = soapObject.getProperty("lookUpString6");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpString6 = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookUpString6 = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookUpString7"))
        {
            Object obj = soapObject.getProperty("lookUpString7");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpString7 = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookUpString7 = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookUpString8"))
        {
            Object obj = soapObject.getProperty("lookUpString8");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpString8 = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookUpString8 = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookUpString9"))
        {
            Object obj = soapObject.getProperty("lookUpString9");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpString9 = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookUpString9 = (String) obj;
            }
        }
        if (soapObject.hasProperty("lookUpstring10"))
        {
            Object obj = soapObject.getProperty("lookUpstring10");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lookUpstring10 = j.toString();
            }else if (obj!= null && obj instanceof String){
                lookUpstring10 = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return comments;
            case 1:
                return lookDate10;
            case 2:
                return lookDate10Specified;
            case 3:
                return lookDate6;
            case 4:
                return lookDate6Specified;
            case 5:
                return lookDate7;
            case 6:
                return lookDate7Specified;
            case 7:
                return lookDate8;
            case 8:
                return lookDate8Specified;
            case 9:
                return lookDate9;
            case 10:
                return lookDate9Specified;
            case 11:
                return lookUp1;
            case 12:
                return lookUp1Specified;
            case 13:
                return lookUp2;
            case 14:
                return lookUp2Specified;
            case 15:
                return lookUp3;
            case 16:
                return lookUp3Specified;
            case 17:
                return lookUp4;
            case 18:
                return lookUp4Specified;
            case 19:
                return lookUp5;
            case 20:
                return lookUp5Specified;
            case 21:
                return lookUp6;
            case 22:
                return lookUp6Specified;
            case 23:
                return lookUp7;
            case 24:
                return lookUp7Specified;
            case 25:
                return lookUp8;
            case 26:
                return lookUp8Specified;
            case 27:
                return lookUp9;
            case 28:
                return lookUp9Specified;
            case 29:
                return lookUpCode;
            case 30:
                return lookUpCodeSpecified;
            case 31:
                return lookUpDate;
            case 32:
                return lookUpDateSpecified;
            case 33:
                return lookUpDate2;
            case 34:
                return lookUpDate2Specified;
            case 35:
                return lookUpDate3;
            case 36:
                return lookUpDate3Specified;
            case 37:
                return lookUpDate4;
            case 38:
                return lookUpDate4Specified;
            case 39:
                return lookUpDate5;
            case 40:
                return lookUpDate5Specified;
            case 41:
                return lookUpFee;
            case 42:
                return lookUpFeeSpecified;
            case 43:
                return lookUpString;
            case 44:
                return lookUpString2;
            case 45:
                return lookUpString3;
            case 46:
                return lookUpString4;
            case 47:
                return lookUpString5;
            case 48:
                return lookUpString6;
            case 49:
                return lookUpString7;
            case 50:
                return lookUpString8;
            case 51:
                return lookUpString9;
            case 52:
                return lookUpstring10;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 53;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "comments";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookDate10";
                break;
            case 2:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookDate10Specified";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookDate6";
                break;
            case 4:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookDate6Specified";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookDate7";
                break;
            case 6:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookDate7Specified";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookDate8";
                break;
            case 8:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookDate8Specified";
                break;
            case 9:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookDate9";
                break;
            case 10:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookDate9Specified";
                break;
            case 11:
                info.type = Double.class;
                info.name = "lookUp1";
                break;
            case 12:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookUp1Specified";
                break;
            case 13:
                info.type = Double.class;
                info.name = "lookUp2";
                break;
            case 14:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookUp2Specified";
                break;
            case 15:
                info.type = Double.class;
                info.name = "lookUp3";
                break;
            case 16:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookUp3Specified";
                break;
            case 17:
                info.type = Double.class;
                info.name = "lookUp4";
                break;
            case 18:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookUp4Specified";
                break;
            case 19:
                info.type = Double.class;
                info.name = "lookUp5";
                break;
            case 20:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookUp5Specified";
                break;
            case 21:
                info.type = Double.class;
                info.name = "lookUp6";
                break;
            case 22:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookUp6Specified";
                break;
            case 23:
                info.type = Double.class;
                info.name = "lookUp7";
                break;
            case 24:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookUp7Specified";
                break;
            case 25:
                info.type = Double.class;
                info.name = "lookUp8";
                break;
            case 26:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookUp8Specified";
                break;
            case 27:
                info.type = Double.class;
                info.name = "lookUp9";
                break;
            case 28:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookUp9Specified";
                break;
            case 29:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "lookUpCode";
                break;
            case 30:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookUpCodeSpecified";
                break;
            case 31:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookUpDate";
                break;
            case 32:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookUpDateSpecified";
                break;
            case 33:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookUpDate2";
                break;
            case 34:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookUpDate2Specified";
                break;
            case 35:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookUpDate3";
                break;
            case 36:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookUpDate3Specified";
                break;
            case 37:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookUpDate4";
                break;
            case 38:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookUpDate4Specified";
                break;
            case 39:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookUpDate5";
                break;
            case 40:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookUpDate5Specified";
                break;
            case 41:
                info.type = Double.class;
                info.name = "lookUpFee";
                break;
            case 42:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "lookUpFeeSpecified";
                break;
            case 43:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookUpString";
                break;
            case 44:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookUpString2";
                break;
            case 45:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookUpString3";
                break;
            case 46:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookUpString4";
                break;
            case 47:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookUpString5";
                break;
            case 48:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookUpString6";
                break;
            case 49:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookUpString7";
                break;
            case 50:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookUpString8";
                break;
            case 51:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookUpString9";
                break;
            case 52:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lookUpstring10";
                break;
        }
    }
    
    @Override
    public String getInnerText() {
        return null;
    }
    
    
    @Override
    public void setInnerText(String s) {
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
