package com.Wsdl2Code.WebServices.WSAmandaService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 1/24/2016 9:16:23 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import com.Wsdl2Code.WebServices.WSAmandaService.KvmSerializable_ws;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class wsValidSub implements KvmSerializable_ws {
    
    public int subCode;
    public String subDesc;
    
    public wsValidSub(){}
    
    public wsValidSub(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("subCode"))
        {
            Object obj = soapObject.getProperty("subCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                subCode = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                subCode = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("subDesc"))
        {
            Object obj = soapObject.getProperty("subDesc");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                subDesc = j.toString();
            }else if (obj!= null && obj instanceof String){
                subDesc = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return subCode;
            case 1:
                return subDesc;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 2;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "subCode";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "subDesc";
                break;
        }
    }
    
    @Override
    public String getInnerText() {
        return null;
    }
    
    
    @Override
    public void setInnerText(String s) {
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
